ChatBox/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from ChatBox import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^chat/', include("chat.urls", namespace="chat")),
    url(r'^sign up/$', views.sign_up, name="sign_up"),
    url(r'^update info/$', views.update_info, name="update_info"),
    url(r'^login/$', views.loginer, name="login"),
    url(r'^accounts/login/$', views.loginer, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^contact us/$', views.contact_us, name="contact-us"),
    # url(r'^respond/$', views.respond, name="respond"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url

from chat import views

urlpatterns = [
    url(r'^$', views.chat_box_posts, name='chat'),

    url(r'^friends/$', views.friends, name='friends'),
    url(r'^find friends/$', views.find_friends, name='find_friends'),
    url(r'^friend request/', views.request_friend, name="friend_request"),
    url(r'^friend accepted/$', views.confirm_friend, name='confirm_friend'),

    url(r'^messages/$', views.messages_list, name="messages"),
    url(r'^messages/admin/$', views.admin_respond, name="admin_respond"),
    url(r'^messages/users/$', views.messages_by_user, name="messages_by_user"),
    url(r'^message seen/$', views.message_seen, name='message_seen'),

    url(r'^comment/$', views.post_comment, name='post_comment'),
    url(r'^like/$', views.like_unlike, name='like/unlike'),
    url(r'^share/$', views.share, name='share'),
]

chat/models.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, validate_comma_separated_integer_list
from django.db import models
from autoslug import AutoSlugField

# Create your models here.


class Profile(models.Model):
    """ Users Profile or Personal information """
    GENDERCHOICES = (("Male", "Male"), ("Female", "Female"), ("Decline to identify", "Decline to identify"))

    picture = models.ImageField(upload_to='images', default='nick.jpg')
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=105)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone Number")
    phone = models.CharField(max_length=17, validators=[phone_regex])
    email = models.EmailField(max_length=150)
    birthday = models.DateTimeField()
    gender = models.CharField(max_length=30, choices=GENDERCHOICES)
    description = models.TextField(null=True, blank=True)
    friends = models.CharField(
        max_length=100000,
        default="",
        validators=[validate_comma_separated_integer_list]
    )
    slug = AutoSlugField(populate_from='username')

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class FriendMessage(models.Model):
    """ Messages that just has a title and text for staff to send to user and Vias varsa.
    Also is used to make Friend Request"""
    from_user = models.CharField(max_length=105)
    to_user = models.ForeignKey(Profile)
    title = models.CharField(max_length=150, null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Chat(models.Model):
    """ Main Blog message.

        Really three types of Chat's a Post a Comment and a Private Message. A Post has a title and has sharing
    options while a Comment and Private Message is only text and image. A Private Message has the sharing option of
    Private Message while a Comment is Public but only displayed occoding to the the preference of the parent Post.
    A comment is either a comment on a post or another comment which is a comment on a post. A private Message is just
    like a text messaging between two users.

        They are four sharing choices: 1) Public - the post is seen by anyone who is logged in 2) Friends - the post is
    only shown to friends. 3) Only Me - the post is only shown to the user himself. 4) Private Message - the post
    is only showed to the user and a posific friend he chose.   All messages are seen the the staff.
    """
    SHARINGCHOICES = (
        ("Public", "Public"),
        ("Friends", "Friends"),
        ("Only Me", "Only Me"),
        ("Private Message", "Private Message")
    )
    comment = models.ForeignKey('self', null=True, blank=True, default=None)
    distance_from_sourse = models.PositiveIntegerField(default=1)
    likes = models.CharField(
        max_length=100000,
        default="",
        validators=[validate_comma_separated_integer_list]
    )
    private_message = models.ForeignKey(Profile, null="True")

    amount_likes = models.IntegerField(default=0)
    title = models.CharField(max_length=400, default="Post", null=True, blank=True)
    image = models.ImageField(upload_to='images',
                              null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    share = models.CharField(max_length=50, choices=SHARINGCHOICES)
    user = models.ForeignKey(Profile, related_name='user')
    users = models.ManyToManyField(Profile, null=True, related_name='users')
    time_posted = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        if self.title == "Post":
            if self.text:
                return "Text: {}".format(self.text)
            else:
                return "pk: {}".format(self.pk)
        return self.title

    def clean(self):
        if self.comment == self:
            raise ValidationError("a chat cant be a comment on its self")

chat/forms.py
from django import forms

from chat import models


def must_be_empty(value):
    """ raises a ValidationError if "value" has a value"""
    if value:
        raise forms.ValidationError('is not empty')


class ChatPostForm(forms.ModelForm):
    """ Form to post a new Post. Has all four elements: image, title, text and share """
    class Meta:
        model = models.Chat
        fields = ['image', 'title', 'text', 'share']

    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty],
                               )

    def clean(self):
        cleaned_data = super().clean()
        image = cleaned_data.get('image')
        text = cleaned_data.get('text')

        if not image and not text:
            raise forms.ValidationError("You need to post an image or a text")


class CommentForm(forms.ModelForm):
    """ Form to post a comment or a post a send a Private Message. It only has a image and text. """
    class Meta:
        model = models.Chat
        fields = ['image', 'text']

    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty],
                               )

    def clean(self):
        cleaned_data = super().clean()
        image = cleaned_data.get('image')
        text = cleaned_data.get('text')
        if not image and not text:
            raise forms.ValidationError("You need to post an image or a text")

ChatBox/views.py
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from ChatBox import forms
from chat import models


def home(request):
    """ Redirects user to main page if logged in or to login in page if not.
    If user has no friends it will redirect to a page to find friends """
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('chat:chat'))
    if request.user.is_authenticated:
        user = models.Profile.objects.get(username=request.user.username)
        friends = user.friends.split(",")
        if len(friends) <= 1:
            return HttpResponseRedirect(reverse('chat:find_friends'))
        return HttpResponseRedirect(reverse('chat:chat'))
    else:
        return HttpResponseRedirect(reverse('login'))


def contact_us(request):
    """  View with form for user to send a message to the staff. Allows even one who is not logged in to sign up. """
    form = forms.ContactStaffForm(request.POST or None)
    if form.is_valid():
        admin = models.Profile.objects.get(username="ChatBox staff")
        if request.user.is_authenticated and request.user.is_staff == False:
            user = models.Profile.objects.get(username=request.user.username)
        else:
            user = models.Profile.objects.get(username="No One")
        message = form.save(commit=False)
        message.from_user = user
        message.to_user = admin
        message.save()
        messages.success(request, "Message was received by our staff. We will contact you soon.")
        if request.user.is_authenticated and request.user.is_staff == False:
            models.FriendMessage.objects.create(
                to_user=user,
                from_user=admin,
                title="We got your " + message.title + " message. We will contact you soon addressing your message."
            )
        return HttpResponseRedirect(reverse('home'))
    return render(request, "contact-us.html", {'form': form, 'message_type': 'contact_us'})


def loginer(request):
    """ logs in user """
    form = forms.LoginForm()
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.add_message(request, messages.SUCCESS, "Login successful!")
                    return HttpResponseRedirect(reverse('home'))
                else:
                    messages.add_message(request, messages.ERROR, "This account has been disabled sorry!")
                    return HttpResponseRedirect(reverse('home'))
            else:
                messages.add_message(request, messages.ERROR, "Invalid Login!")
    return render(request, 'login.html', {'form': form})


def sign_up(request):
    """ Page the User fills out form to sign up. """
    title = "Sign Up"
    form = forms.ProfileForm()
    if request.method == "POST":
        form = forms.ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            username = form.cleaned_data['first_name'] + " " + form.cleaned_data['last_name']
            # if User.objects.filter(username=username):
            #    messages.error(request, "Sorry that name or password is already taken")
            #    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
            profile = form.save(commit=False)
            profile.picture = form.cleaned_data['picture']
            profile.username = username
            profile.save()

            user = User.objects.create_user(
                username=profile.username,
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password']
            )
            login(request, user)
            new_user = models.Profile.objects.get(username=request.user.username)
            new_user.friends = str(new_user.pk)
            new_user.save()

            messages.success(request, "You are all signed up.")
            return HttpResponseRedirect(reverse('chat:find_friends'))
    return render(request, 'profile_form.html', {"form": form, "title": title})


@login_required()
def update_info(request):
    title = "Update Info"
    if request.user.is_staff:
        messages.error(request, "This page is only for users to change there account info.")
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    user = models.Profile.objects.get(username=request.user.username)
    form = forms.ProfileUpdateForm(instance=user)
    password_form = forms.UpdatePasswordForm(request.POST or None)
    user_info = request.user
    if request.method == "POST":
        form = forms.ProfileUpdateForm(request.POST, request.FILES, instance=user)
        description = request.POST.get("description")
        if form.is_valid() and password_form.is_valid():
            username = form.cleaned_data['first_name'] + " " + form.cleaned_data['last_name']
            if User.objects.filter(username=username) and user_info.username != username:
                messages.error(request, "Sorry that name or password is already taken")
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
            else:
                user_info.username = username
                user_info.email = form.cleaned_data['email']
                if password_form.is_valid() and password_form.cleaned_data['password'] != "":
                    print("HERE is the password:   " + password_form.cleaned_data['password'])
                    user_info.set_password(password_form.cleaned_data['password'])
                else:
                    print("Password is empty. The password is not changed")
                user_info.save()

                data = form.save(commit=False)
                if description and description != "None":
                    data.description = description
                data.picture = form.cleaned_data['picture']
                data.username = username
                data.save()
                new_user_info = authenticate(
                    username=data.username,
                    email=data.email
                )
                login(request, new_user_info)
                messages.success(request, "Info Updated")
                return HttpResponseRedirect(reverse('chat:friends'))
    return render(request, 'profile_form.html', {"form": form, 'password_form': password_form,
                                                 'title': title, 'user': user})


def logout_view(request):
    """ logs out user """
    logout(request)
    messages.add_message(request, messages.SUCCESS, "Logout Successfully!")
    return HttpResponseRedirect(reverse('home'))

chat/templates/chat/ajax.html
{% load staticfiles %}

<!-- all the ajax requests. Its in HTML page so it could use Django templatetags -->

<script>

    $(document).ready(function() {

     // chatbox.html

        // this ajax submits the comment form
    $(".submit-comment").click(function (event) {
        event.preventDefault();
        var formData = $(this).parent(".comment-form").serialize();
        var $form = $(this).parent(".comment-form");
        var image = $(this).siblings('.image-field').children("#image").val();
        var text = $(this).siblings("#text").val();
        var type = $(this).siblings(".type").val();
        console.log(formData);
        if (image) {
            alert("Need to reload to be able to save image");
            $(this).parent(".comment-form").submit();

        } else if (text === "") {
            alert("Post not posted. Add a picture or a post");
        } else {
            $.ajax({
                type: "POST",
                url: "{% url 'chat:post_comment' %}",
                data: formData,
                success: function (data) {
                    if (type === "private") {
                        newPost = '<div class="thumbnail user-message" style="float: right;">';
                        newPost += '<div class="caption"><h3>';
                        newPost += '<img src="{{ user.picture.url }}" class="profile_pic"/>';
                        newPost += ' Post <small> from <a href="" class="name">{{ user }}</a>';
                        newPost += '</small></h3>';
                        newPost += '<p>' + data.comment + '</p>';
                        newPost += '<p></p>';
                    } else {
                        $form.css("display", "none");
                        var newPost = '<p><img src="{{ user.picture.url }}" class="profile_pic"/> ';
                        newPost += '<a href="" class="name">{{ user }}</a>';
                        newPost += ' ' + data.comment + '</p>';
                    }
                    $form.siblings(".new-post").prepend(newPost);
                    $form.siblings("p").children(".reply").css("display", "inline");

                },
                error: function (error) {
                    alert("Didn't work");
                    $(this).parent(".comment-form").submit();
                }
            });
        }
    });


    // comment_loop.html

    // Like button
    $(".like-unlike-form").submit(function (event) {
        // likes and likes posts
        event.preventDefault();
        var data = $(this).serialize();
        $.ajax({
            type: "POST",
            data: data,
            url: "{% url 'chat:like/unlike' %}",
            success: function (data) {
                $("#like-button-"+data.post_pk).children(".like-button-icon").remove();

                if (data.flash_message == "liked!") {
                    $("#like-form-"+data.post_pk).children(".like-text").text("Unlike");
                    $("#like-button-"+data.post_pk).html("<i class='fa fa-thumbs-up like-button-icon' aria-hidden='true'></i>");
                } else {
                    $("#like-form-"+data.post_pk).children(".like-text").text("Like");
                    $("#like-button-"+data.post_pk).html('<i class="fa fa-thumbs-o-up like-button-icon" aria-hidden="true"></i>');
                }
                if (data.likes > 0) {
                    $("#like-form-"+data.post_pk).siblings(".likes").css("display", "inline").text(data.likes + " likes");
                } else {
                    $("#like-form-"+data.post_pk).siblings(".likes").text("");
                }
            },
            error: function (error) {
                alert("didn't work");
                console.log(error.status + ": " + error.statusText);
            }
        })
    });

    // share button. shares the post
    $('.share-form').submit(function (event) {
        // s ahres the post
        event.preventDefault();
        var data = $(this).serialize();
        $.ajax({
            type: "POST",
            data: data,
            url: "{% url 'chat:share' %}",
            success: function (data) {
                $("#share-form-" + data.post_pk).css("display", "none");
                var newText = "<h5>";
                newText += '<img src="{{ user.picture.url }}" class="profile_pic"/>';
                newText += '<a href="" class="name">{{ user }}</a> shared <strong>' + data.post_title + '</strong>';
                newText += "</h5>";
                $("#new-ajax-sharer-" + data.post_pk).html(newText);
            },
            error: function (error) {
                alert(error.status + ": " + error.statusText);
                // $(".share-form").submit();
            }
        });
    });


        // friends.html - find_friends.html

        // Asks for friend request
        $(".friend_request").click(function(event) {
            event.preventDefault();
            var pk = $(this).siblings(".pk").val();
            var data = {
                friend: pk
            };
            $.ajax({
                type: "GET",
                url: "{% url 'chat:friend_request' %}",
                data: data,
                success: function (data) {
                    $("#friend_" + pk + " .friend_request").fadeOut();
                    message = "Friend Request sent!";
                    $("#friend-request-" + pk).html(message);
                },
                error: function (responce, error) {
                    alert("Didn't Go");
                    $("#friend_" + pk).submit();
                }
            })
        });


        // messages.html

        // deletes message
        $(".message_seen").click(function(event) {
            event.preventDefault();
            var pk = parseInt($(this).prevAll(".message_pk").val());
            var data = {
                message_pk: pk,
            };
            $.ajax({
                type: "GET",
                url: "{% url 'chat:message_seen' %}",
                data: data,
                success: function (data) {
                    $("#message_" + pk).parents(".message_box").fadeOut();
                    $("#message-box-" + pk).fadeOut();
                },
                error: function (responce, error) {
                    alert("Didn' t Go");
                    $("#message_" + pk).submit();
                }
            })
        });

        // respond to message
        $(".respond-form").submit(function (event) {
            event.preventDefault();
            data = $(this).serialize();
            var message = $(this).children("#id_message").val();
            if (message === "") {
                alert("Message not sent you need add a message");
            } else {
            $.ajax({
                type: "POST",
                {% if request.user.is_staff %}
                    url: "{% url 'chat:messages' %}",
                {% else %}
                    url: "{% url 'chat:admin_respond' %}",
                {% endif %}
                data: data,
                success: function(data) {

                    alert("Message sent");
                },
                error: function(error) {
                    $(".respond-form").submit();
                    alert("Couldn't be sent");
                }
            })
            }
        });

        // Confirms friend
        $(".confirm_friend").click(function(event) {
            event.preventDefault();
            var numbbb = parseInt($(this).prevAll("input[type='hidden']").val());
            var data = {
                message_pk: numbbb,
            };
            $.ajax({
                type: "GET",
                url: "{% url 'chat:confirm_friend' %}",
                data: data,
                success: function (data) {
                    $("#friend_request_" + numbbb).fadeOut();
                    $("#message-box-" + numbbb).fadeOut();
                },
                error: function (responce, error) {
                    $("#friend_request_" + numbbb).submit();
                }

            })

        });
    });
</script>

chat/templates/chat/find_friends.html
{% extends 'chat/friends.html' %}
<!-- Page that shows are users and has a search option that returns people in the search -->

<script>
    {% block javascript %}
    {% endblock %}
</script>

{% block title %}Find Friends{% endblock %}

{% block search_results %}
    <!-- On top of page. For Admin and to send message if we couldn't find anything occorinding to the post -->
    {% if request.user.is_staff %}
        <div class="col-sm-10 col-sm-offset-1">
        <p class="no-margin">Admin they are <strong>{{ users_friends }}</strong> users</p>
        </div>
    {% endif %}
    {% if friends|length == 0 %}
        <div class="col-sm-10 col-sm-offset-1">
        <div class="thumbnail">
            <div class="friends-no">
        <p>We couldn't find anything for <strong>{{ search }}</strong></p>
        <p>Looking for people or posts? Try entering a name, location, or different words.</p>
            </div>
        </div>
        </div>
    {% endif %}
{% endblock %}

{% block find_friends_user %}
    <!-- Returns the box with users info -->
    <h2 style="color: blueviolet">{{ user.username }} is You!</h2>
    {% include 'chat/user_info_box.html' %}
{% endblock %}

{% block friend_request %}
    <!--has button with friend request-->
    <form id="friend_{{ friend.pk }}" style="display: inline-flex;" method="GET" href="{% url 'chat:friend_request' %}">
        <input type="hidden" class="pk" name="friend" value="{{ friend.pk }}" >
        {% if friend == user  %}
            <h4 class="chocolate">This is you!</h4>
            {% elif request.user.is_staff %}
        {% elif friend in your_friends%}
            <h4 style="color: red">This is your friend already!</h4>
        {% else %}
            <input type="submit" class="btn btn-primary friend_request"  role="button" value="Make Friend Request!">
            <h2 id="friend-request-{{ friend.pk }}" class="chocolate"></h2>
        {% endif %}
    </form>
{% endblock %}

chat/templates/chat/message_loop.html
{% load staticfiles %}


<div class="thumbnail col-sm-10 col-sm-offset-1 thirty-space" id="message-box-{{ message.pk }}">
            <div class="caption ">
                <!-- message for friend request, friend accepted and general-->
                {% if message.title == "Friend Request" %}
                    <h3>Friend Request from {{ message.from_user }}</h3>
                    <p>{{ message.from_user }} requested that you should be his friend. By accepting You will see all his chats and he will yours</p>

                    {% elif message.title == "Friend Accepted" %}
                            <h3>Friend Request accepted from {{ message.from_user }}</h3>
                            <p>{{ message.from_user }} accepted your friend requested. Now you will see all his chats and he will see yours.</p>
                        {% else %}
                            <h3>{% if message.title %}{{ message.title}}{% endif %}</h3>
                            {% if message.message %}
                                <p>{{ message.message }}</p>
                            {% endif %}
                            <p>from <strong><a href="#">{{ message.from_user }}</a></strong></p>
                    {% endif %}

                <!-- Button to delete post -->
                <form id="message_{{ message.pk }}" method="get" action="{% url 'chat:message_seen'%}">
                    <input type="hidden" class="message_pk" value="{{ message.pk }}" name="message_pk">
                    {% if message.title == 'Friend Request' %}
                        <input type="submit" style="float: right;" class="btn btn-danger message_seen" role="button" value="Delete Request">
                    {% else %}
                        <input type="submit" style="float:right;  " class="btn btn-danger message_seen btn-big" role="button" value="X">
                    {% endif %}
                </form>

                <!-- Button to accept friend  -->
                {% if message.title == "Friend Request" %}
                    <form id="friend_request_{{ message.pk }}" method="get" action="{% url 'chat:confirm_friend'%}">
                        <input type="hidden" class="message_pk" value="{{ message.pk }}" name="message_pk">
                        <input type="submit" class="btn btn-primary confirm_friend" role="button" value="Accept Friend Reqeust!">
                    </form>

                <!-- Form to send first Message to your new friend or start conversation -->
                {% elif message.title == "Friend Accepted" %}
                    <form class="" style="" method="POST" action="{% url 'chat:post_comment' %}"
                                                enctype="multipart/form-data">
                        {% csrf_token %}
                        <textarea name="text" class="comment-text-form" id="text" placeholder="text"></textarea>
                        <div class="image-field">
                        {# // where image input will be placed in jquery code#}
                        </div>
                        <button class="btn-danger hidden-items image-link">X</button>
                        <button class="btn-info image-link" id="image-button"><i
                                class="fa fa-camera-retro fa-1.5x camera-icon" aria-hidden="true"></i>
                        </button>
                        <input type="hidden" name="username" value="{{ message.from_user }}">
                        <input type="hidden" class="type" name="type" value="private">
                        <input type="submit" class="btn btn-primary" value="Start Chat with {{ message.from_user }}"/>
                    </form>

                    <!-- Respond form  -->
                {% else %}
                    {% if message.from_user != "No One" %}
                    <button class="btn btn-primary respond">Respond</button>
                        {% else %}
                        <br>
                    {% endif %}
                    <br>
                    {% if request.user.is_staff %}
                    <form method="POST" class="respond-form" action="{% url 'chat:admin_respond' %}" style="display: none" enctype="multipart/form-data">
                        <br>
                        <input type="hidden" name="username" value="{{ message.from_user }}">
                        <label for="id_message">Message:</label>
                        <p><textarea cols="40" id="id_message" name="message" rows="10"></textarea></p>
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Send Message">
                    </form>
                    {% else %}
                    <form method="POST" class="respond-form" action="{% url 'chat:messages' %}" style="display: none" enctype="multipart/form-data">
                        <h4>{{ form.title }}</h4>
                        <label for="id_message">Message:</label>
                        <p>{{ form.message }}</p>
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Send Message">
                    </form>
                    {% endif %}
                {% endif %}
            </div>
            </div>

chat/templates/chat/post_chat.html
{% extends "layout.html" %}

{% block title %}Post to ChatBox!{% endblock %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
    <h1>Post a message or image to ChatBox!</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        <p id="title">{{ form.title }}</p>
        <p id="image">{{ form.image }}</p>
        <p id="text">{{ form.text }}</p>
        <p id="share"><select id="id_share" name="share" required>
            <option value="" selected="selected">-----------</option>
            <option value="Public">Public</option>
            {% if num_friends > 0 %}
                <option value="Friends">Friends</option>
            {% endif %}
            <option value="Only Me">Only Me</option>
            <option value="Private Message">Private Message</option>
        </select></p>
        <input id="only-me" type="text" placeholder="share with" name="share_with"style="display: none">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Post">
    </form>
    </div>
{% endblock %}