ChatBox/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from ChatBox import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='home'),
    url(r'^chat/', include("chat.urls", namespace="chat")),
    url(r'^sign up/$', views.sign_up, name="sign_up"),
    url(r'^update info/$', views.update_info, name="update_info"),
    url(r'^login/$', views.loginer, name="login"),
    url(r'^accounts/login/$', views.loginer, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^contact us/$', views.contact_us, name="contact-us"),
    # url(r'^respond/$', views.respond, name="respond"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url

from chat import views

urlpatterns = [
    url(r'^$', views.chat_box_posts, name='chat'),

    url(r'^friends/$', views.friends, name='friends'),
    url(r'^find friends/$', views.find_friends, name='find_friends'),
    url(r'^friend request/', views.request_friend, name="friend_request"),
    url(r'^friend accepted/$', views.confirm_friend, name='confirm_friend'),

    url(r'^messages/$', views.messages_list, name="messages"),
    url(r'^messages/admin/$', views.admin_respond, name="admin_respond"),
    url(r'^messages/users/$', views.messages_by_user, name="messages_by_user"),
    url(r'^message seen/$', views.message_seen, name='message_seen'),

    url(r'^comment/$', views.post_comment, name='post_comment'),
    url(r'^like/$', views.like_unlike, name='like/unlike'),
    url(r'^share/$', views.share, name='share'),
]

chat/models.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, validate_comma_separated_integer_list
from django.db import models
from autoslug import AutoSlugField

# Create your models here.


class Profile(models.Model):
    """ Users Profile or Personal information """
    GENDERCHOICES = (("Male", "Male"), ("Female", "Female"), ("Decline to identify", "Decline to identify"))

    picture = models.ImageField(upload_to='images', default='nick.jpg')
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=105)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone Number")
    phone = models.CharField(max_length=17, validators=[phone_regex])
    email = models.EmailField(max_length=150)
    birthday = models.DateTimeField()
    gender = models.CharField(max_length=30, choices=GENDERCHOICES)
    description = models.TextField(null=True, blank=True)
    friends = models.CharField(
        max_length=100000,
        default="",
        validators=[validate_comma_separated_integer_list]
    )
    slug = AutoSlugField(populate_from='username')

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class FriendMessage(models.Model):
    """ Messages that just has a title and text for staff to send to user and Vias varsa.
    Also is used to make Friend Request"""
    from_user = models.CharField(max_length=105)
    to_user = models.ForeignKey(Profile)
    title = models.CharField(max_length=150, null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Chat(models.Model):
    """ Main Blog message.

        Really three types of Chat's a Post a Comment and a Private Message. A Post has a title and has sharing
    options while a Comment and Private Message is only text and image. A Private Message has the sharing option of
    Private Message while a Comment is Public but only displayed occoding to the the preference of the parent Post.
    A comment is either a comment on a post or another comment which is a comment on a post. A private Message is just
    like a text messaging between two users.

        They are four sharing choices: 1) Public - the post is seen by anyone who is logged in 2) Friends - the post is
    only shown to friends. 3) Only Me - the post is only shown to the user himself. 4) Private Message - the post
    is only showed to the user and a posific friend he chose.   All messages are seen the the staff.
    """
    SHARINGCHOICES = (
        ("Public", "Public"),
        ("Friends", "Friends"),
        ("Only Me", "Only Me"),
        ("Private Message", "Private Message")
    )
    comment = models.ForeignKey('self', null=True, blank=True, default=None)
    distance_from_sourse = models.PositiveIntegerField(default=1)
    likes = models.CharField(
        max_length=100000,
        default="",
        validators=[validate_comma_separated_integer_list]
    )
    private_message = models.ForeignKey(Profile, null="True")

    amount_likes = models.IntegerField(default=0)
    title = models.CharField(max_length=400, default="Post", null=True, blank=True)
    image = models.ImageField(upload_to='images',
                              null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    share = models.CharField(max_length=50, choices=SHARINGCHOICES)
    user = models.ForeignKey(Profile, related_name='user')
    users = models.ManyToManyField(Profile, null=True, related_name='users')
    time_posted = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        if self.title == "Post":
            if self.text:
                return "Text: {}".format(self.text)
            else:
                return "pk: {}".format(self.pk)
        return self.title

    def clean(self):
        if self.comment == self:
            raise ValidationError("a chat cant be a comment on its self")

templates/contact-us.html
{% extends "layout.html" %}

<!-- Form to contact the The Patrika staff -->

{% block title %}contact us{% endblock %}

{% block content %}
    <div class="col-sm-10 col-sm-offset-1">
        <h1 class="no-margin">{% if message_type == "contact_us" %}Send a message to The Patrika team{% else %}
            Respond{% endif %}
        </h1>
        <form method="POST" action="" enctype="multipart/form-data">
            <h4>{{ form.title }}</h4>
            <label for="id_message">Message: </label>
            <p>{{ form.message }}</p>
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Send Message">
        </form>
    </div>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

<!-- This page is not used anymore. now the urls automtically redirects user to chatbox.html or login.html if user is not logged in -->

{% block title %}The Patrika{% endblock %}

{% block content %}
    <h3>Welcome to The Patrika</h3>
    <p>You are not logged in. Log in or if your new Sign up!!!!!!</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"  content="The Patrika site">
    <meta name="content"  content="News Site, The Patrika, Bml Munjal ">
    <meta name="author" content="Python Project">
    <title>{% block title %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/costom_styles.css' %}">
    {% block css %}{% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery.min.js" type="text/javascript"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://malsup.github.com/jquery.form.js"></script>
    <meta class="foundation-mq">
</head>

<body>
<!-- nav bar on top of page. it will aleays be on top -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <h4 class="navbar-brand chatbox-brand"><a href="{% url 'chat:chat' %}" >The Patrika!</a></h4>
    </div>

    <div class="collapse navbar-collapse collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            {% block submenu %}{% endblock %}
            {% if request.user.is_authenticated %}
                <!-- dropbox to search posts or people -->
                <li class="dropdown">
                    <a href="#" data-target="#" data-toggle="dropdown" role="button" aria-haspopup="true" class="dropdown-toggle message-dropdown" aria-expanded="false">Search (Post/People) <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><form class="navbar-form navbar-left" method="get" name="tabForm" autocomplete="">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q" placeholder="Search" value="{{ request.GET.q }}"/>
                            </div>
                            <input type="button" class="search-button btn btn-primary" value="Search Posts" onclick="searchButton();"/>
                            <input type="button" style="" id="submit-find-friends" class="btn btn-info" value="Find Friends" onclick="findFriends();"/>
                        </form>
                        </li>
                    </ul>
                </li>

                {% if request.user.is_staff %}
                    <li class=""><a href="{% url 'chat:messages' %}">Messages</a></li>
                {% else %}
                    <li class=""><a href="{% url 'chat:messages' %}">Messages/Notifications</a></li>
                    <li class=""><a href="{% url 'chat:friends' %}">Personal Info</a></li>
                    <li class=""><a href="{% url 'contact-us' %}">Contact Us</a></li>
                {% endif %}
                <li class=""><a href="{% url 'logout' %}">Logout</a></li>
                <!-- If user is not logged in -->
            {% else %}
                <li class=""><a href="{% url 'sign_up' %}">Sign up</a></li>
                <li class=""><a href="{% url 'login' %}">Login</a></li>
                <li class=""><a href="{% url 'contact-us' %}">Contact Us</a></li>
            {% endif %}
        </ul>
    </div>
    </div>
</nav>



<div class="container top-page-margin">
    <!-- Messages are send here -->
    {% if messages %}
        <div class="container" style="margin-bottom: 50px;">
            {% for flash_message in messages %}
                <div class="alert alert-{% if flash_message.tags == "error" %}danger{% else %}{{ flash_message.tags }}{% endif %} text-center">
                <p>{{ flash_message.tags }}</p>
                <p>{{ flash_message }}</p>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

<!-- tell admin he is logged in as admin ontop of page -->
{% if user.is_superuser %}
    <h1>Admin</h1>
{% endif %}

    <!-- all the content of each page -->
    {% block content %}{% endblock %}
</div>

<footer class="row columns">
    <hr/>
    <div class="small-6 columns">
        <p class="logo" style="">&copy; The Patrika</p>
    </div>
</footer>

<!-- some function -->
<script>

    function searchButton() {
        document.tabForm.action = "{% url 'chat:chat' %}";
        // document.tabForm.target = "_blank";
        document.tabForm.submit();
    }

    function findFriends() {
        document.tabForm.action = "{% url 'chat:find_friends' %}";
        // document.tabForm.target = "_blank";
        document.tabForm.submit();
    }
    $(document).ready(function () {
        {%  block javascript %}{%  endblock %}
    });
</script>
<script src="{% static 'js/jquery.js' %}"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

<!-- Page to log in acts to /login/ or account/login/ -->

{% block title %}Login{% endblock %}

{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        <h1 class="no-margin login-margin">Welcome to The Patrika!</h1>
        <p class="login-p">You are not logged in. Login or you could <a href="{% url 'sign_up' %}"><strong>Sign up</strong></a></p>
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-default" value="Login">
        </form>
    </div>
{% endblock %}

208

templates/profile_form.html
{% extends "layout.html" %}

<!-- Sign up form and form to update info -->

{% block title %}{{ title }}!{% endblock %}

{% block content %}
    <div class="col-sm-8 col-sm-offset-1">
    <h1 class="no-margin twenty-space">{{ title }}!</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% if message_type == "response" %}
            <p>{{ form.message }}</p>
        {% else %}
            {{  form.as_p }}
            {% if title == "Update Info" %}
                <label>Description:</label>
                <textarea class="form-control" style="" rows="4" placeholder="describe yourself" name="description" >{{ user.description }}</textarea>

                <h2 class="twenty-space">Edit Password</h2>
                {{ password_form.as_p }}
            {% endif %}
        {% endif %}
        {% csrf_token %}
        <input type="submit" class="btn btn-info twenty-space five-top" value="{{ title }}">
    </form>
    </div>
{% endblock %}